FROM dustynv/ros:foxy-pytorch-l4t-r32.6.1

# 安装驱动
RUN apt-get update
RUN apt-get install python3-serial
RUN apt-get install python3-gi

# 安装webtool依赖库
RUN pip install tornado
RUN pip install pymongo

# 设置时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p /root/ros2_ws

WORKDIR /root/ros2_ws

CMD ["/root/ros2_ws/entrypoint.sh"]
